export { default as About } from './About'
export { default as Clients } from './Clients'
export { default as Hero } from './Hero'
export { default as OurClients } from './OurClients'
export { default as OurProject } from './OurProjects'
export { default as Services } from './Services'
export { default as SuccessfulStory } from './SuccessfulStory'
export { default as Technologies } from './Technologies'
