export { default as About } from './About'
export { default as Clients } from './Clients'
export { default as Hero } from './Hero'
export { default as OurClients } from './ourClients'
export { default as OurProject } from './ourProjects'
export { default as Services } from './Services'
export { default as SuccessfulStory } from './successfulStory'
export { default as Technologies } from './Technologies'
